framework:
    cache:
        app: cache.adapter.redis
        default_redis_provider: '%redis.dsn%'
        pools:
            cache_pool:
                adapter: cache.adapter.redis
                default_lifetime: 300
                tags: true
