version: "3.4"

x-api: &api-template
  build:
    context: .
    dockerfile: local.Dockerfile
  environment:
    XDEBUG_CONFIG: "remote_host=192.168.1.3 remote_enable=1"
    PHP_IDE_CONFIG: "serverName=xdebug"
  env_file:
    - .env
  volumes:
    - .:/var/www/html
    - ./config/php/www.conf:/usr/local/etc/php-fpm.d/www.conf

services:
  gateway:
    container_name: xm-gateway
    image: nginx:latest
    env_file:
      - .env
    depends_on:
      - api
    volumes:
      - "./config/nginx/vhost.local.conf:/etc/nginx/conf.d/default.conf:ro"
      - "./public:/var/www/public:ro"
    ports:
      - ${GATEWAY_PORT:-8000}:80

  api:
    container_name: xm-api
    <<: *api-template
    networks:
      default:
        aliases:
          - api

  postgres:
    container_name: xm-postgres
    image: postgres:12.1
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5435:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      default:
        aliases:
          - postgres

  redis:
    container_name: xm-redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=1
      - REDIS_PORT=6379
      - REDIS_DATABASES=16

volumes:
  api_cache:
  api_logs:
  api_vendors:
  postgres:
